name: Deploy to GitHub Pages
on:
  push:
    branches: [gh-pages]
  workflow_dispatch:
  workflow_run:
    workflows: ["Run ElizaOS Daily Task", "Run Hyperfy Discord Daily Task"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - run: |
          echo '<!DOCTYPE html><html><head><title>Directory Listing</title><style>body{font-family:Arial}</style></head><body><h1>Files</h1>' > index.html
          find . -type d -not -path "*/\.*" | sort | while read -r dir; do
            dirname=${dir#./}
            echo "<div><a href=\"$dirname/\">$dirname/</a></div>" >> index.html
          done
          find . -type f -not -path "*/\.*" | sort >> index.html
          echo '</body></html>' >> index.html
          touch .nojekyll

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v4
